### ISSUE TITLE
List of listy things.

### ISSUE THREAD

**Issue by Claycorp** [TheTemportalist/Compression#1]
Possible options and idears.
- Compressed objects retain use. Edible, Throwable, Useable.
- Compressed blocks retain stats. Hardness, Explosion resistance.
- /Dev/null like inventory to set what is inside. Also allows you to remove items.
- Upgradeable to "Black Hole mode" Where it picks up items when being put into chests.

https://github.com/CCM-Modding/Compresstion

**Comment by TheTemportalist** [comment]
What effect should eating compressed food have?

**Comment by TheTemportalist** [comment]
@Claycorp see http://jenkins.dries007.net/view/Temportal/job/Compression/1/
