### ISSUE TITLE
Crash when clicking on an item in JEI

### ISSUE THREAD

**Issue by MoxieGrrl** [TheTemportalist/Compression#11]
When opening the inventory and trying to click on a Neotech battery to get the recipe, the game crashes to desktop. [Crash report.](http://pastebin.com/FrHz6Hkn)

**Comment by TheTemportalist** [comment]
Has this been reported to Neotech? it looks like its their baked class which is doing the erroring (despite being caused by Compression).
java.lang.NullPointerException: Rendering item
    at com.teambr.bookshelf.client.models.BakedDynItem.func_188616_a(BakedDynItem.java:78)

**Comment by TheTemportalist** [comment]
specifically this line:
https://github.com/TeamBR-Modding/Bookshelf/blob/1.9/src/main/scala/com/teambr/bookshelf/client/models/BakedDynItem.java#L78

**Comment by Insufficient-Charge** [comment]
I have something to add to this. This is also happening with the E-flux mod. I reported this to the author of JEI and he said to report it here. Seeing a similar issue, I guess I'll report it here. Some of the items are crashing when you look up a recipe from any mod in the game it appears. More commonly with Neotech and E-flux, but, whatever it is that's causing this, is happening within Compression.
https://github.com/mezz/JustEnoughItems/issues/276#issuecomment-219570728

**Comment by TheTemportalist** [comment]
Ultimately this is a team Bookshelf issue. Their BakedDynItem assumes its textures are non-null. The next release, however, will include the ability to blackllist items. That way they dont cause crashes.

**Comment by TheTemportalist** [comment]
See https://github.com/TheTemportalist/Compression/commit/37ff879b2a3f208efff36c2c10a137ba6199bc11

**Comment by TheTemportalist** [comment]
When it gets approved, this is the version you will want http://minecraft.curseforge.com/projects/compression/files/2302966
