### ISSUE TITLE
NPE Crash with RFTools

### ISSUE THREAD

**Issue by Thiana** [TheTemportalist/Compression#4]
Hi again ;)

Another NPE crash for you, this time with RFTools. Crash report is at http://openeye.openmods.info/crashes/0ed3ba654ffc5fe472427796aa717659. Log is at http://pastebin.com/UJ8Njh3Y. I'm reporting here first again but I can report it to McJty if you'd prefer?

To reproduce, create an instance with RFTools (4.10), McJtyLib (1.7.10), Origin (1.7.10-7.1.0), Compression (0.0.4), CoFHLib (1.7.10-1.0.3-175). Start MC, Crash :) Remove either mod and it starts fine.

A simple workaround is to add "mcjty.rftools.items.dimlets.KnownDimlet" to the Item Class Blacklist.

Thanks.

**Comment by Thiana** [comment]
Oops, make that RFTools 4.01

**Comment by Thiana** [comment]
Oops, make that RFTools 4.0.1 and McJtyLib 1.7.0.

**Comment by TheTemportalist** [comment]
Ok. So it looks like I have to do some tinkering with my catch statement, because mod compatibility. Ill keep this open, and I have some ideas, but I cant work on it right this moment.
