### ISSUE TITLE
The compressed block does not decrease in size.

### ISSUE THREAD

**Issue by Ashymad** [TheTemportalist/Compression#7]
Right clicking with any compressed block doesn't decrease its size, so it's possible to clone endlessly any block  Just to be sure I've made another instance with only Forge, Origin and Compression and it happens there as well. I've wondered if it's maybe a feature for worlds with cheats, so I've started new survival world and within minutes I had my endless supply of cobble.

Tested with:
Compression 0.0.9 (I believe it happens on other versions as well)
Origin 8.0.3
Forge 10.13.4.1558 (stable)
Minecraft 1.7.10
MultiMC 0.4.11-751 win32
Java 8u73 x64
Windows 8.1 x64

**Comment by TheTemportalist** [comment]
This has been patched in 1.9.4
