### ISSUE TITLE
things with NBT can not be compressed.

### ISSUE THREAD

**Issue by dmodoomsirius** [TheTemportalist/Compression#8]

**Comment by TheTemportalist** [comment]
Metadata can be compressed to Single compressed, but single to double of metadata returns double with metadata 0

**Comment by TheTemportalist** [comment]
cannot decompress any metadata compressed

**Comment by TheTemportalist** [comment]
https://github.com/TheTemportalist/Compression/commit/777d26962351c10c10664ac9df9695c72ec3c4d9
